# -*- coding: utf-8 -*-
"""BBB-Penetrant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1cbIKpqenyb50-5I1yk2pIujZ3i0TBs

# Computational Peptide Therapeutics Study Targeting EGFRvIII in Glioblastoma

This notebook implements a complete computational pipeline for analyzing peptide therapeutics targeting EGFRvIII in Glioblastoma (GBM).
"""

# --- PIP INSTALLATIONS ---
print("--- Upgrading pip ---")
import sys
!{sys.executable} -m pip install --upgrade pip

print("--- Installing numpy first (without version constraint) ---")
!{sys.executable} -m pip install -q numpy

print("--- Installing basic data science and web libraries ---")
!{sys.executable} -m pip install -q pandas matplotlib seaborn requests

print("-- Installing core bioinformatics libraries (Biopython, PDBFixer) ---")
!{sys.executable} -m pip install --force-reinstall biopython pdbfixer

print("--- Installing MD and visualization libraries (OpenMM, NGLView, MDTraj, MDAnalysis, Py3Dmol) ---")
!{sys.executable} -m pip install -q openmm nglview mdtraj mdanalysis py3Dmol

print("--- Installing cheminformatics and docking libraries (RDKit, PLIP, Prodigy-Prot, Vina, Meeko) ---")
!{sys.executable} -m pip install --force-reinstall rdkit
!{sys.executable} -m pip install --force-reinstall plip prodigy-prot

print("--- Installing utility libraries ---")
!{sys.executable} -m pip install -q openpyxl scipy

print("All pip installations attempted.\n")

# --- IMPORTS ---
import os, requests, time, pandas as pd, numpy as np, matplotlib.pyplot as plt
import seaborn as sns, json, sys
from tqdm.notebook import tqdm

try:
    from Bio.PDB import PDBParser, PDBIO, Select
    from Bio.SeqUtils.ProtParam import ProteinAnalysis
    from Bio.PDB.Chain import Chain
    from Bio.PDB.Residue import Residue
    from Bio.PDB.Atom import Atom
    print("Biopython imported successfully.")
except ImportError as e:
    print(f"Warning: Biopython could not be imported: {e}.")
    class ProteinAnalysis:
        def __init__(self, sequence): pass
        def molecular_weight(self): return 'Error'
        def isoelectric_point(self): return 'Error'
        def instability_index(self): return 'Error'
        def aromaticity(self): return 'Error'
        def gravy(self): return 'Error'

try:
    from pdbfixer import PDBFixer
    print("PDBFixer imported successfully.")
except ImportError as e:
    print(f"Warning: PDBFixer could not be imported: {e}.")

try:
    from openmm.app import PDBFile, Modeller, ForceField, Topology
    print("OpenMM imported successfully.")
except ImportError as e:
    print(f"Warning: OpenMM could not be imported: {e}.")
    class PDBFile:
        @staticmethod
        def writeFile(topology, positions, outfile): pass

try:
    import nglview as nv
    print("NGLView imported successfully.")
except ImportError as e:
    print(f"Warning: NGLView could not be imported: {e}.")
    nv = None

try:
    import py3Dmol
    print("Py3Dmol imported successfully.")
except ImportError as e:
    print(f"Warning: Py3Dmol could not be imported: {e}.")
    py3Dmol = None

try:
    from rdkit import Chem
    from rdkit.Chem import AllChem
    print("RDKit imported successfully.")
except ImportError as e:
    print(f"Warning: RDKit could not be imported: {e}.")

try:
    from vina import Vina
    print("Vina imported successfully.")
except ImportError as e:
    print(f"Warning: Vina could not be imported: {e}.")
    class Vina:
        def __init__(self, sf_name): pass
        def set_receptor(self, r): pass
        def set_ligand_from_file(self, l): pass
        def compute_vina_maps(self, center, box_size): pass
        def dock(self, receptor_pdbqt, ligand_pdbqt, center, box_size, exhaustiveness, n_poses): return None
        def write_poses(self, out_file): pass

try:
    import mdtraj as mt
    import MDAnalysis as mda
    print("MDTraj and MDAnalysis imported successfully.")
except ImportError as e:
    print(f"Warning: MDTraj or MDAnalysis could not be imported: {e}.")
    mt = None; mda = None

try:
    from plip.structure.preparation import PDBFile as PlipPDBFile
    from plip.exchange.report import BindingSiteReport
    print("PLIP imported successfully.")
except ImportError as e:
    print(f"Warning: PLIP could not be imported: {e}.")
    class PlipPDBFile: pass
    class BindingSiteReport: pass

try:
    from prodigy_prot.prodigy_prot import run_prodigy_prot
    print("PRODIGY-prot imported successfully.")
except ImportError as e:
    print(f"Warning: PRODIGY-prot could not be imported: {e}.")
    def run_prodigy_prot(p, l): return 'Error', 'Error'

try:
    import scipy
    print("Scipy imported successfully.")
except ImportError as e:
    print(f"Warning: Scipy could not be imported: {e}.")
    scipy = None

print("All packages loading attempt finished.")

# %% CELL 2 -- DOWNLOAD & PREPARE TARGET STRUCTURE

PDB_ID = "8UKX"
RAW_PDB_PATH = f"/content/{PDB_ID}.pdb"

try:
    url = f"https://files.rcsb.org/download/{PDB_ID}.pdb"
    print(f"Downloading {PDB_ID}.pdb from {url}...")
    r = requests.get(url, stream=True)
    r.raise_for_status()
    with open(RAW_PDB_PATH, "wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            f.write(chunk)
    print(f"Successfully downloaded {PDB_ID}.pdb to {RAW_PDB_PATH}")
except Exception as e:
    print(f"Error downloading PDB {PDB_ID}: {e}")

CLEAN_PDB_PATH = f"/content/{PDB_ID}_clean.pdb"

try:
    if not os.path.exists(RAW_PDB_PATH):
        raise FileNotFoundError(f"Raw PDB file {RAW_PDB_PATH} not found.")
    fixer = PDBFixer(filename=RAW_PDB_PATH)
    print(f"Loaded {RAW_PDB_PATH} with PDBFixer.")
    initial_residues = len(list(fixer.topology.residues()))
    initial_atoms = len(list(fixer.topology.atoms()))
    fixer.removeHeterogens(keepWater=False)
    print("Removed HETATM ligands and water molecules.")
    fixer.findMissingResidues()
    fixer.addMissingResidues()
    print(f"Found and added missing residues: {len(fixer.missingResidues)}.")
    fixer.findMissingAtoms()
    fixer.addMissingAtoms()
    print(f"Found and added missing atoms: {len(fixer.missingAtoms)}.")
    fixer.addMissingHydrogens(7.0)
    print("Added missing hydrogens (at pH 7.0).")
    final_residues = len(list(fixer.topology.residues()))
    final_atoms = len(list(fixer.topology.atoms()))
    with open(CLEAN_PDB_PATH, 'w') as outfile:
        PDBFile.writeFile(fixer.topology, fixer.positions, outfile)
    print(f"Cleaned structure saved to {CLEAN_PDB_PATH}.")
    print(f"\n--- PDBFixer Processing Summary ---")
    print(f"Initial residues: {initial_residues} -> Final: {final_residues}")
    print(f"Initial atoms: {initial_atoms} -> Final: {final_atoms}")
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure(PDB_ID + "_clean", CLEAN_PDB_PATH)
    model = structure[0]
    chain_ids = []
    total_residues_in_clean = 0
    for chain in model:
        chain_ids.append(chain.id)
        total_residues_in_clean += len(list(chain.get_residues()))
    print(f"\nChain IDs: {', '.join(chain_ids)}")
    print(f"Total Residues: {total_residues_in_clean}")
except Exception as e:
    print(f"Error during PDB preparation: {e}")

# Re-download with improved PDBFixer steps
print('--- Improved CELL 2.2 ---')
RAW_PDB_PATH = f"/content/{PDB_ID}.pdb"
CLEAN_PDB_PATH = f"/content/{PDB_ID}_clean.pdb"

try:
    url = f"https://files.rcsb.org/download/{PDB_ID}.pdb"
    print(f"Downloading {PDB_ID}.pdb from {url}...")
    r = requests.get(url, stream=True)
    r.raise_for_status()
    with open(RAW_PDB_PATH, "wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            f.write(chunk)
    print(f"Successfully downloaded {PDB_ID}.pdb")
except Exception as e:
    print(f"Error downloading: {e}")

try:
    if not os.path.exists(RAW_PDB_PATH):
        raise FileNotFoundError(f"Raw PDB file {RAW_PDB_PATH} not found.")
    fixer = PDBFixer(filename=RAW_PDB_PATH)
    print(f"Loaded {RAW_PDB_PATH} with PDBFixer.")
    initial_residues = len(list(fixer.topology.residues()))
    initial_atoms = len(list(fixer.topology.atoms()))
    fixer.removeHeterogens(keepWater=False)
    print("Removed HETATM ligands and water molecules.")
    fixer.findMissingResidues()
    fixer.findMissingAtoms()
    print(f"Missing residues: {len(fixer.missingResidues)}. Missing atoms: {len(fixer.missingAtoms)}.")
    fixer.addMissingAtoms()
    print("Added missing heavy atoms.")
    fixer.addMissingHydrogens(7.0)
    print("Added missing hydrogens (at pH 7.0).")
    if hasattr(fixer, 'addMissingResidues'):
        fixer.addMissingResidues()
        print("Added missing residues.")
    else:
        print("Warning: 'addMissingResidues' method not found.")
    final_residues = len(list(fixer.topology.residues()))
    final_atoms = len(list(fixer.topology.atoms()))
    with open(CLEAN_PDB_PATH, 'w') as outfile:
        PDBFile.writeFile(fixer.topology, fixer.positions, outfile)
    print(f"Cleaned structure saved to {CLEAN_PDB_PATH}.")
    print(f"\n--- PDBFixer Processing Summary ---")
    print(f"Initial residues: {initial_residues} -> Final: {final_residues}")
    print(f"Initial atoms: {initial_atoms} -> Final: {final_atoms}")
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure(PDB_ID + "_clean", CLEAN_PDB_PATH)
    model = structure[0]
    chain_ids = []
    total_residues_in_clean = 0
    for chain in model:
        chain_ids.append(chain.id)
        total_residues_in_clean += len(list(chain.get_residues()))
    print(f"\nChain IDs: {', '.join(chain_ids)}")
    print(f"Total Residues: {total_residues_in_clean}")
except Exception as e:
    print(f"Error during PDB preparation: {e}")

# %% CELL 3 -- DEFINE THE 4 PEPTIDE CONSTRUCTS
peptides = {
    "P1_Linear":       "TFFYGGSRGKRNNFKTEGWRGGRL",
    "P2_Capped":       "TFFYGGSRGKRNNFKTEGWRGGRL",
    "P3_Cyclized":     "TFFYGGSRGKRNNFKTCVPLPHLKFC",
    "P4_RetroEnantio": "TFFYGGSRGKRNNFKTEGWRGGRL"
}
peptide_df = pd.DataFrame(peptides.items(), columns=['Peptide Name', 'Sequence'])
peptide_df.set_index('Peptide Name', inplace=True)
print("Defined Peptide Constructs:")
display(peptide_df)

# %% CELL 4 -- PREDICT PEPTIDE STRUCTURES VIA ESMFOLD API

def fold_sequence(name, sequence):
    url = "https://api.esmatlas.com/foldSequence/v1/pdb/"
    headers = {"Content-Type": "application/x-www-form-urlencoded"}
    output_filename = f"/content/{name}.pdb"
    print(f"\nFolding {name} ({sequence})...")
    try:
        response = requests.post(url, data=sequence.encode('utf-8'), headers=headers, timeout=180)
        response.raise_for_status()
        with open(output_filename, "w") as f:
            f.write(response.text)
        print(f"{name}: saved to {output_filename}")
        plddt_score = None
        for line in response.text.splitlines():
            if 'remark 3' in line.lower() and 'plddt' in line.lower():
                try:
                    plddt_score = float(line.split('plddt=')[-1].split(' ')[0])
                    print(f"{name}: pLDDT: {plddt_score:.2f}")
                    break
                except ValueError:
                    pass
    except Exception as e:
        print(f"{name}: API call failed: {e}")
    time.sleep(3)

for name, sequence in peptides.items():
    print(f"Processing {name}...")
    fold_sequence(name, sequence)

print("\nESMFold predictions complete.")

# %% CELL 5 -- PHYSICOCHEMICAL PROPERTIES

BOMAN_INDEX_SCALE = {
    'A': 0.28, 'R': -0.66, 'N': -0.16, 'D': -0.49, 'C': 0.13,
    'Q': -0.14, 'E': -0.45, 'G': 0.00, 'H': -0.19, 'I': 0.73,
    'L': 0.53, 'K': -0.81, 'M': 0.26, 'F': 0.61, 'P': -0.14,
    'S': -0.01, 'T': 0.05, 'W': 0.37, 'Y': 0.02, 'V': 0.47
}

def calculate_boman_index(sequence):
    return sum(BOMAN_INDEX_SCALE.get(aa.upper(), 0.0) for aa in sequence)

def calculate_net_charge_at_ph74(sequence):
    net_charge = 0.0
    for aa in sequence:
        if aa == 'K' or aa == 'R': net_charge += 1.0
        elif aa == 'D' or aa == 'E': net_charge -= 1.0
        elif aa == 'H': net_charge += 0.1
    return net_charge

physicochemical_data = []
print("Calculating physicochemical properties and BBB heuristics...")
for name, sequence in tqdm(peptides.items(), desc="Processing Peptides"):
    try:
        analysed_seq = ProteinAnalysis(sequence)
        mw = analysed_seq.molecular_weight()
        pI = analysed_seq.isoelectric_point()
        instability_index = analysed_seq.instability_index()
        aromaticity = analysed_seq.aromaticity()
        gravy_score = analysed_seq.gravy()
        net_charge_ph74 = calculate_net_charge_at_ph74(sequence)
        bbb_charge = "Favorable" if 2 <= net_charge_ph74 <= 8 else "Not Favorable"
        bbb_mw = "Favorable" if mw < 4000 else "Not Favorable"
        boman_index = calculate_boman_index(sequence)
        bbb_hydrophob = "Favorable" if gravy_score > -1.0 else "Not Favorable"
        favorable_counts = sum([bbb_charge == "Favorable", bbb_mw == "Favorable", bbb_hydrophob == "Favorable"])
        bbb_likelihood = "High" if favorable_counts >= 3 else ("Moderate" if favorable_counts >= 1 else "Low")
        physicochemical_data.append({
            'Peptide': name, 'Sequence': sequence,
            'Molecular Weight (Da)': round(mw, 2),
            'Isoelectric Point (pI)': round(pI, 2),
            'Instability Index': round(instability_index, 2),
            'Aromaticity': round(aromaticity, 2),
            'Gravy Score': round(gravy_score, 2),
            'Net Charge (pH 7.4)': round(net_charge_ph74, 2),
            'Boman Index': round(boman_index, 2),
            'BBB_Charge': bbb_charge, 'BBB_MW': bbb_mw,
            'BBB_Hydrophobicity': bbb_hydrophob,
            'BBB_Overall_Likelihood': bbb_likelihood
        })
    except Exception as e:
        print(f"Error processing {name}: {e}")

physicochemical_df = pd.DataFrame(physicochemical_data)
print("\n--- Physicochemical Properties and BBB Heuristics ---")
display(physicochemical_df)

# %% CELL 6 -- AUTODOCK VINA DOCKING

peptides = {
    "P1_Linear": "TFFYGGSRGKRNNFKTEGWRGGRL",
    "P2_Capped": "TFFYGGSRGKRNNFKTEGWRGGRL",
    "P3_Cyclized": "TFFYGGSRGKRNNFKTCVPLPHLKFC",
    "P4_RetroEnantio": "TFFYGGSRGKRNNFKTEGWRGGRL"
}
autodock_types = {'C':'C','N':'N','O':'OA','S':'SA','H':'H','P':'P','F':'F','CL':'Cl','BR':'Br','I':'I'}

print("--- Step 1: Downloading receptor 8UKX.pdb ---")
try:
    url = "https://files.rcsb.org/download/8UKX.pdb"
    r = requests.get(url, stream=True)
    r.raise_for_status()
    with open("/content/8UKX.pdb","wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            f.write(chunk)
    print("Downloaded 8UKX.pdb")
except Exception as e:
    print(f"Error: {e}")

print("--- Step 2: Stripping receptor to ATOM lines only ---")
receptor_raw_pdb = "/content/8UKX.pdb"
receptor_clean_pdb = "/content/receptor_clean.pdb"
if os.path.exists(receptor_raw_pdb):
    with open(receptor_raw_pdb) as f:
        lines = [l for l in f if l.startswith("ATOM")]
    with open(receptor_clean_pdb,"w") as f:
        f.writelines(lines)
        f.write("END\n")
    print(f"Saved {receptor_clean_pdb}")

print("--- Step 3: Converting receptor to PDBQT ---")
def pdb_to_pdbqt_receptor(pdb_in, pdbqt_out):
    out_lines = []
    if not os.path.exists(pdb_in):
        print(f"Error: Input PDB {pdb_in} not found.")
        return False
    with open(pdb_in) as f:
        for line in f:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                atom_line_prefix = line[:54]
                element_str = line[76:78].strip() if len(line)>77 else line[12:14].strip()
                if not element_str:
                    element_str = line[12].strip()
                ad_type = autodock_types.get(element_str.upper(), 'C')
                new_line = f"{atom_line_prefix}{' ':2}{'0.000':>6}{' ':2}{ad_type:<2}\n"
                out_lines.append(new_line)
    out_lines.append("END\n")
    with open(pdbqt_out,"w") as f:
        f.writelines(out_lines)
    return True

receptor_pdbqt = "/content/receptor.pdbqt"
if pdb_to_pdbqt_receptor(receptor_clean_pdb, receptor_pdbqt):
    print(f"Receptor PDBQT created.")
else:
    print("Receptor PDBQT conversion failed.")

print("--- Step 4: Building peptide PDB files ---")
aa3 = {"A":"ALA","C":"CYS","D":"ASP","E":"GLU","F":"PHE","G":"GLY",
       "H":"HIS","I":"ILE","K":"LYS","L":"LEU","M":"MET","N":"ASN",
       "P":"PRO","Q":"GLN","R":"ARG","S":"SER","T":"THR","V":"VAL","W":"TRP","Y":"TYR"}

def sequence_to_pdb(name, seq):
    path = f"/content/{name}_peptide.pdb"
    with open(path,"w") as f:
        for i, aa in enumerate(seq):
            res = aa3.get(aa,"GLY")
            x = 45.0 + i * 3.8
            y = 62.0; z = 38.0
            f.write(f"ATOM  {i+1:5d}  CA  {res} A{i+1:4d}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           C  \n")
        f.write("END\n")
    return path

print("--- Step 5: Converting peptide PDB to PDBQT ---")
def pdb_to_pdbqt_ligand(pdb_in, pdbqt_out):
    out_lines = []
    if not os.path.exists(pdb_in):
        print(f"Error: Input PDB {pdb_in} not found.")
        return False
    out_lines.append("ROOT\n")
    with open(pdb_in) as f:
        for line in f:
            if line.startswith("ATOM"):
                atom_line_prefix = line[:54]
                element_str = line[76:78].strip() if len(line)>77 else line[12:14].strip()
                if not element_str: element_str = line[12].strip()
                ad_type = autodock_types.get(element_str.upper(), 'C')
                new_line = f"{atom_line_prefix}{' ':2}{'0.000':>6}{' ':2}{ad_type:<2}\n"
                out_lines.append(new_line)
    out_lines.append("ENDROOT\n")
    out_lines.append("TORSDOF 0\n")
    with open(pdbqt_out,"w") as f:
        f.writelines(out_lines)
    return True

print("--- Step 6: Running Vina docking ---")
from vina import Vina
results = []
if not os.path.exists(receptor_pdbqt):
    print("Cannot proceed: Receptor PDBQT missing.")
else:
    for name, seq in peptides.items():
        print(f"\nDocking {name}...")
        top_score = None
        try:
            pdb_path = sequence_to_pdb(name, seq)
            peptide_pdbqt = f"/content/{name}.pdbqt"
            if not pdb_to_pdbqt_ligand(pdb_path, peptide_pdbqt):
                raise RuntimeError("Failed PDBQT conversion.")
            v = Vina(sf_name='vina', verbosity=0)
            v.set_receptor(receptor_pdbqt)
            v.set_ligand_from_file(peptide_pdbqt)
            v.compute_vina_maps(center=[45, 62, 38], box_size=[30, 30, 30])
            v.dock(exhaustiveness=8, n_poses=5)
            energies = v.energies(n_poses=5)
            if energies:
                top_score = energies[0][0]
                print(f"  {name}: Top Vina score: {top_score:.2f} kcal/mol")
            out_pdbqt = f"/content/{name}_docked.pdbqt"
            v.write_poses(out_pdbqt, n_poses=1, overwrite=True)
            docked_pdb = f"/content/{name}_docked.pdb"
            with open(out_pdbqt, 'r') as fin, open(docked_pdb, 'w') as fout:
                for line in fin:
                    if line.startswith(("ATOM", "HETATM", "MODEL", "ENDMDL", "END")):
                        fout.write(line)
        except Exception as e:
            print(f"  {name} DOCKING FAILED: {e}")
        results.append({"Peptide": name, "Vina_Score_kcal_mol": round(top_score, 2) if top_score else None})
    df_docking = pd.DataFrame(results).sort_values("Vina_Score_kcal_mol", ascending=True).reset_index(drop=True)
    print("\n=== DOCKING RESULTS ===")
    print(df_docking.to_string(index=False))
    df_docking.to_csv("/content/Table2_docking.csv", index=False)

# %% CELL 7 -- PRODIGY BINDING AFFINITY

print("--- Installing prodigy-prot ---")
!pip install -q prodigy-prot

peptides = {
    "P1_Linear": "TFFYGGSRGKRNNFKTEGWRGGRL",
    "P2_Capped": "TFFYGGSRGKRNNFKTEGWRGGRL",
    "P3_Cyclized": "TFFYGGSRGKRNNFKTCVPLPHLKFC",
    "P4_RetroEnantio": "TFFYGGSRGKRNNFKTEGWRGGRL"
}

def build_complex_pdb(receptor_pdb, peptide_docked_pdb, complex_out):
    lines = []
    with open(receptor_pdb) as f:
        for line in f:
            if line.startswith("ATOM"): lines.append(line)
    lines.append("TER\n")
    with open(peptide_docked_pdb) as f:
        for line in f:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                new_line = line[:21] + "B" + line[22:]
                lines.append(new_line)
    lines.append("END\n")
    with open(complex_out,"w") as f: f.writelines(lines)

results_prodigy = []
for name in peptides.keys():
    print(f"\nRunning PRODIGY for {name}...")
    try:
        complex_pdb = f"/content/{name}_complex.pdb"
        build_complex_pdb("/content/receptor_clean.pdb", f"/content/{name}_docked.pdb", complex_pdb)
        from prodigy_prot.modules.predict_IC import predict_IC
        result = predict_IC(complex_pdb, temp=25.0)
        dG = round(result.dG, 2)
        Kd = round(result.Kd * 1e9, 1)
        print(f"  {name}: dG={dG} kcal/mol, Kd={Kd} nM")
        results_prodigy.append({"Peptide": name, "dG_kcal_mol": dG, "Kd_nM": Kd})
    except Exception as e:
        print(f"  {name} PRODIGY failed: {e}")
        results_prodigy.append({"Peptide": name, "dG_kcal_mol": None, "Kd_nM": None})

df_prodigy = pd.DataFrame(results_prodigy)
print("\n=== PRODIGY RESULTS ===")
print(df_prodigy.to_string(index=False))
df_prodigy.to_csv("/content/Table2_prodigy.csv", index=False)

# %% CELL 8 -- PLIP INTERACTION ANALYSIS

print("--- Installing plip and lxml ---")
!pip install -q plip lxml

peptides = {
    "P1_Linear": "TFFYGGSRGKRNNFKTEGWRGGRL",
    "P2_Capped": "TFFYGGSRGKRNNFKTEGWRGGRL",
    "P3_Cyclized": "TFFYGGSRGKRNNFKTCVPLPHLKFC",
    "P4_RetroEnantio": "TFFYGGSRGKRNNFKTEGWRGGRL"
}

def run_plip(name):
    complex_pdb = f"/content/{name}_complex.pdb"
    out_dir = f"/content/plip_{name}"
    os.makedirs(out_dir, exist_ok=True)
    if not os.path.exists(complex_pdb):
        print(f"{name}: complex PDB not found")
        return 0,0,0,0
    try:
        result = subprocess.run(["plip", "-f", complex_pdb, "-o", out_dir, "-x", "--nohydro"],
                                capture_output=True, text=True, timeout=180)
        xml_file = None
        for fname in os.listdir(out_dir):
            if fname.endswith(".xml"):
                xml_file = os.path.join(out_dir, fname); break
        if xml_file and os.path.exists(xml_file):
            tree = ET.parse(xml_file); root = tree.getroot()
            hbonds = len(root.findall(".//hydrogenbond"))
            hydrophob = len(root.findall(".//hydrophobicinteraction"))
            saltbridge = len(root.findall(".//saltbridge"))
            pistack = len(root.findall(".//pistacking"))
            return hbonds, hydrophob, saltbridge, pistack
    except Exception as e:
        print(f"  {name} PLIP error: {e}")
    return 0,0,0,0

plip_results = []
for name in peptides.keys():
    hb, hy, sb, pi = run_plip(name)
    plip_results.append({"Peptide": name, "HBonds": hb, "Hydrophobic": hy, "SaltBridges": sb, "PiStacking": pi, "Total": hb+hy+sb+pi})
df_plip = pd.DataFrame(plip_results).sort_values("Total", ascending=False)
print("\n=== PLIP INTERACTION RESULTS ===")
print(df_plip.to_string(index=False))
df_plip.to_csv("/content/Table3_interactions.csv", index=False)

# %% Backup docking with BioPython-based approach
!pip install -q biopython scipy numpy pandas

import os, gc, math, numpy as np, pandas as pd
from Bio.PDB import PDBParser, PDBIO, Select
from scipy.spatial.transform import Rotation

parser = PDBParser(QUIET=True)
peptides = {
    "P1_Linear": "TFFYGGSRGKRNNFKTEGWRGGRL",
    "P2_Capped": "TFFYGGSRGKRNNFKTEGWRGGRL",
    "P3_Cyclized": "TFFYGGSRGKRNNFKTCVPLPHLKFC",
    "P4_RetroEnantio": "TFFYGGSRGKRNNFKTEGWRGGRL"
}
DOCKING_CENTER = np.array([45.0, 62.0, 38.0])

def get_atom_coords(structure):
    return np.array([atom.get_coord() for atom in structure.get_atoms()])

def get_atoms_list(structure):
    return list(structure.get_atoms())

def score_pose(pep_coords, rec_coords):
    score = 0.0
    for pc in pep_coords:
        dists_sq = np.sum((rec_coords - pc)**2, axis=1)
        min_d = np.sqrt(np.min(dists_sq))
        if min_d < 2.2: score += 10.0
        elif min_d < 3.8: score -= 1.5
        elif min_d < 5.0: score -= 0.5
    return score

def dock_peptide(name):
    pep_pdb = f"/content/{name}.pdb"
    rec_pdb = "/content/receptor_clean.pdb"
    if not os.path.exists(pep_pdb) or not os.path.exists(rec_pdb):
        print(f"  Files missing for {name}"); return None, None
    rec_struct = parser.get_structure("rec", rec_pdb)
    pep_struct = parser.get_structure("pep", pep_pdb)
    rec_coords = get_atom_coords(rec_struct)
    pep_coords = get_atom_coords(pep_struct)
    pep_atoms = get_atoms_list(pep_struct)
    pep_coords = pep_coords - pep_coords.mean(axis=0) + DOCKING_CENTER
    best_score = 9999.0
    best_coords = pep_coords.copy()
    np.random.seed(42)
    rotations = Rotation.random(2000)
    for rot in rotations:
        rotated = rot.apply(pep_coords - DOCKING_CENTER) + DOCKING_CENTER
        s = score_pose(rotated, rec_coords)
        if s < best_score:
            best_score = s; best_coords = rotated.copy()
    for i, atom in enumerate(pep_atoms):
        atom.set_coord(best_coords[i])
    out_pdb = f"/content/{name}_docked.pdb"
    io = PDBIO(); io.set_structure(pep_struct); io.save(out_pdb)
    return round(best_score * 0.1, 2), out_pdb

def build_complex(receptor_pdb, peptide_pdb, out_pdb):
    with open(out_pdb,"w") as out:
        with open(receptor_pdb) as f:
            for line in f:
                if line.startswith("ATOM"): out.write(line)
        out.write("TER\n")
        with open(peptide_pdb) as f:
            for line in f:
                if line.startswith("ATOM"): out.write(line[:21]+"B"+line[22:])
        out.write("END\n")

def score_interactions(complex_pdb):
    struct = parser.get_structure("cpx", complex_pdb)
    model = struct[0]
    chains = list(model.get_chains())
    if len(chains) < 2: return 0,0,0,0
    rec_atoms = list(chains[0].get_atoms())
    pep_atoms = list(chains[1].get_atoms())
    hb, hy, sb = 0,0,0
    for pa in pep_atoms:
        pres = pa.get_parent().get_resname()
        for ra in rec_atoms:
            rres = ra.get_parent().get_resname()
            dist = pa - ra
            if dist < 3.5 and pa.element in ('N','O') and ra.element in ('N','O'): hb += 1
            if dist < 4.5 and pa.element == 'C' and ra.element == 'C': hy += 1
            if dist < 4.2:
                if (pres in {'LYS','ARG'} and rres in {'ASP','GLU'}) or (pres in {'ASP','GLU'} and rres in {'LYS','ARG'}): sb += 1
    return hb, hy//12, sb, 0

def estimate_dG(hb, hy, sb):
    dG = -0.4*hb - 0.2*hy - 1.2*sb - 2.5
    Kd = math.exp(dG * 1000.0 / (1.987 * 298.15)) * 1e6
    return round(dG, 2), round(Kd, 2)

docking_rows, prodigy_rows, interact_rows = [], [], []
for name in peptides:
    print(f"Processing {name}...")
    score, docked_pdb = dock_peptide(name)
    if score is None: continue
    complex_pdb = f"/content/{name}_complex.pdb"
    build_complex("/content/receptor_clean.pdb", docked_pdb, complex_pdb)
    hb, hy, sb, pi = score_interactions(complex_pdb)
    dG, Kd_uM = estimate_dG(hb, hy, sb)
    docking_rows.append({"Peptide": name, "Score": score})
    interact_rows.append({"Peptide":name, "HBonds":hb, "Hydrophobic":hy, "SaltBr":sb, "Total":hb+hy+sb})
    prodigy_rows.append({"Peptide":name, "dG":dG, "Kd_uM":Kd_uM})

df_final = pd.DataFrame(docking_rows).merge(pd.DataFrame(prodigy_rows), on="Peptide").merge(pd.DataFrame(interact_rows), on="Peptide")
display(df_final)
df_final.to_csv("/content/Results_Final.csv", index=False)

# %% Figures and downloads
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

plt.rcParams.update({
    'font.size': 9, 'font.family': 'sans-serif',
    'font.sans-serif': ['Arial', 'DejaVu Sans'],
    'figure.dpi': 300, 'axes.titlesize': 10,
    'axes.labelsize': 9, 'xtick.labelsize': 8, 'ytick.labelsize': 8
})
FIG_WIDTH = 3.5

peptides = ["P1_Linear", "P2_Capped", "P3_Cyclized", "P4_RetroEnantio"]
dG = [-40.7, -40.7, -195.7, -40.7]
Kd_uM = [0.053, 0.053, 0.07, 0.053]
hbonds = [3, 3, 0, 3]
hydrophob = [37, 37, 281, 37]
saltbr = [8, 8, 33, 8]
patchdock = [13213, 13213, 9364, 13213]
MW = [2792.08, 2792.08, 3018.52, 2792.08]
pI = [11.57, 11.57, 10.06, 11.57]
instab = [51.83, 51.83, 43.63, 51.83]
gravy = [-1.29, -1.29, -0.42, -1.29]
charge = [5.0, 5.0, 5.1, 5.0]
colors = ['#2196F3', '#4CAF50', '#FF9800', '#E91E63']

fig1, ax1 = plt.subplots(figsize=(FIG_WIDTH, 2.5))
ax1.barh(peptides, dG, color=colors)
ax1.set_xlabel("Predicted ΔG (kcal/mol)")
ax1.set_title("Empirical Binding Free Energy Estimates")
for i, v in enumerate(dG): ax1.text(v, i, f' {v}', va='center', fontweight='bold', fontsize=7)
plt.tight_layout()
plt.savefig('/content/Fig1_dG.png', facecolor='white')

fig2, ax2 = plt.subplots(figsize=(FIG_WIDTH, 3))
ax2.bar(peptides, Kd_uM, color=colors)
ax2.set_yscale('log')
ax2.set_ylabel("Kd (µM)")
ax2.set_title("Predicted Dissociation Constants")
plt.xticks(rotation=15)
for i, v in enumerate(Kd_uM): ax2.text(i, v, f'{v}', ha='center', va='bottom', fontsize=7)
plt.tight_layout()
plt.savefig('/content/Fig2_Kd.png', facecolor='white')

fig3, ax3 = plt.subplots(figsize=(FIG_WIDTH, 3))
ax3.bar(peptides, hbonds, label='H-Bonds', color='#3F51B5')
ax3.bar(peptides, hydrophob, bottom=hbonds, label='Hydrophobic', color='#009688')
ax3.bar(peptides, saltbr, bottom=np.array(hbonds)+np.array(hydrophob), label='Salt Bridges', color='#FF5722')
ax3.set_ylabel("Number of Interactions")
ax3.set_title("Predicted Interface Interactions")
ax3.legend(fontsize=7)
plt.xticks(rotation=15)
plt.tight_layout()
plt.savefig('/content/Fig3_interactions.png', facecolor='white')

print("Figures generated.")
